//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProjectC_
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTable
    {
        public int BId { get; set; }
        public string BTitle { get; set; }
        public string BCategory { get; set; }
        public string BDesc { get; set; }
        public string BUrl { get; set; }
    }
}
