//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProjectC_
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RegistrationTable
    {
        
        public int Uid { get; set; }

        [Required(ErrorMessage = "Enter Your Name...")]
        [Display(Name = "Enter your name...")]
        public string Uname { get; set; }

        [Required(ErrorMessage = "Please Enter Your email....")]
        [Display(Name = "Email id....")]
        public string Uemail { get; set; }

        [Required(ErrorMessage = "Enter the password...")]
        [Display(Name = "Password...")]
        [DataType(DataType.Password)]
        public string Upass { get; set; }

        [Required(ErrorMessage = "Select The Gender....")]
        [Display(Name = "Select gender...")]
        public string Ugender { get; set; }
    }
}
